apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-support
  namespace: default
  labels:
    app: chatbot-support
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatbot-support
  template:
    metadata:
      labels:
        app: chatbot-support
    spec:
      containers:
      - name: chatbot-support
        image: 'gcr.io/ai-chatbot-support-444616/chatbot-support:v1'
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: jwt_secret

        ports:
        - containerPort: 3000
