apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend-service
  ports:
    - protocol: TCP
      port: 3000 # External port for accessing the backend
      targetPort: 3000 # Internal container port
  type: ClusterIP # Internal service for backend
