apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: chatbot-support
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: chatbot-support
  endpoints:
  - port: metrics
    interval: 30s

