apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-support-deployment-staging
  labels:
    app: chatbot-support
    env: staging
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: chatbot-support
  template:
    metadata:
      labels:
        app: chatbot-support
    spec:
      containers:
        - image: pioneer18/ai-chatbot-support:v1
          imagePullPolicy: Always
          name: chatbot-support
          env:
            - name: OPENAI_API_KEY
              value: OPENAI_API_KEY
            - name: JWT_SECRET
              value: JWT_SECRET
            - name: POSTGRES_USER
              value: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              value: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: POSTGRES_DB
            - name: DB_PORT
              value: DB_PORT
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "64Mi"
              cpu: "200m"
            limits:
              memory: "128Mi"
              cpu: "300m"
          ports:
            - containerPort: 3000