apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-support-deployment-staging
  labels:
    app: chatbot-support
    env: staging
spec:
  replicas: 2
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: chatbot-support
  template:
    metadata:
      labels:
        app: chatbot-support
    spec:
      containers:
        - image: pioneer18/ai-chatbot-support:v1
          imagePullPolicy: Always
          name: chatbot-support
          env:
            - name: OPENAI_API_KEY
              value: OPENAI_API_KEY
            - name: JWT_SECRET
              value: JWT_SECRET
            - name: POSTGRES_USER
              value: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              value: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: POSTGRES_DB
            - name: DB_PORT
              value: DB_PORT
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
          resources:
            requests:
              memory: "64Mi"
              cpu: "200m"
            limits:
              memory: "128Mi"
              cpu: "300m"
          # readinessProbe:
          #   periodSeconds: 5
          #   exec:
          #     command:
          #       - sh
          #       - -c
          #       - "mkdir -p /tmp && touch /tmp/healthy && cat /tmp/healthy"
          ports:
            - containerPort: 3000
        - image: postgres:latest
          name: postgres
          imagePullPolicy: Always
          env:
            - name: POSTGRES_USER
              value: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              value: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: POSTGRES_DB
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
        - image: redis:latest
          name: redis
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_PORT
              value: "6379"
          resources:
            requests:
              memory: "64Mi"
              cpu: "200m"
            limits:
              memory: "128Mi"
              cpu: "300m"

      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
