apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-support-deployment
  labels:
    app: chatbot-support
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-support
  template:
    metadata:
      labels:
        app: chatbot-support
    spec:
      containers:
        - name: chatbot-support
          image: gcr.io/ai-chatbot-support-444616/chatbot-support:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
