apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-support-deployment-production
  labels:
    app: chatbot-support
    env: production
spec:
  replicas: 2
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: chatbot-support
  template:
    metadata:
      labels:
        app: chatbot-support
    spec:
      containers:
        - image: gcr.io/ai-chatbot-support-444616/chatbot-support:v1
          imagePullPolicy: Always
          name: chatbot-support
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-api-key
                  key: OPENAI_API_KEY
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt_secret
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
            - name: DB
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PORT
          readinessProbe:
            periodSeconds: 5
            exec:
              command:
              - sh
              - -c
              - "mkdir -p /tmp && touch /tmp/healthy && cat /tmp/healthy"
          ports:
            - containerPort: 3000
