apiVersion: v1
kind: Service
metadata:
  name: chatbot-support-service-staging
  labels:
    app: chatbot-support
    env: staging
spec:
  selector:
    app: chatbot-support
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
